version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Applying database migrations..."
      - python manage.py migrate
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput

  build:
    commands:
      - echo "Zipping application for Elastic Beanstalk..."
      - zip -r deploy-package.zip . -x "*.git*" "tests/*" "*.DS_Store"

  post_build:
    commands:
      - echo "Deploying to Elastic Beanstalk..."
      - aws s3 cp deploy-package.zip s3://<YOUR-S3-BUCKET-NAME>/deploy-package.zip
      - aws elasticbeanstalk create-application-version \
          --application-name <YOUR-BEANSTALK-APP-NAME> \
          --version-label "v-$(date +%Y%m%d%H%M%S)" \
          --source-bundle S3Bucket=<YOUR-S3-BUCKET-NAME>,S3Key=deploy-package.zip
      - aws elasticbeanstalk update-environment \
          --environment-name <YOUR-BEANSTALK-ENV-NAME> \
          --version-label "v-$(date +%Y%m%d%H%M%S)"

artifacts:
  files:
    - deploy-package.zip
