# Generated by Django 5.2 on 2025-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreGameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=50)),
                ("store", models.CharField(max_length=100)),
                ("owned_count", models.IntegerField()),
                ("missing_count", models.IntegerField()),
                ("owned_list", models.TextField()),
                ("missing_list", models.TextField()),
            ],
        ),
    ]
